### PR TITLE
Added libftdi1

### PR DESCRIPTION
**Pull request by prabhakarlad**
Signed-off-by: Lad, Prabhakar Prabhakar.Lad@racelogic.co.uk

### CODE REVIEW

**Comment by lundmar** [comment]
Do you need the boost dependency?
It seems both boost and python in extra is quite out of date - python actually breaks building so in effect libftdi1 can not build.

**Comment by prabhakarlad** [comment]
Yes, it does need boost dependency. I got it building with boost version 1.58.0 & python 3.4.3.
with arm-cortex-a8 with linux version 2.6.37

**Comment by lundmar** [comment]
Hmm, are you using the boost and python build files from extra or do you use custom overlayed build files with fixes?

The python build breaks for me on Ubuntu 16.04. Sigh, python is such a mess - for years the Python have neglected to fix cross compilation issues. I'll have to check up on the current state of Python 3 to see if they have fixed anything.

**Comment by prabhakarlad** [comment]
No I build it from extra layer itself.
Weird, python & boost builds without any errors on Ubuntu 15.04

**Comment by lundmar** [comment]
Ok - something in Ubuntu 16.04 must be affecting my build even though it shouldn't. I'll see if I can upgrade and fix the python build.

Thanks for the input.

**Comment by lundmar** [comment]
After some pain I've fixed the python build. It's 2016 an even the latest python release is fundamentally broken. No one in the Python camps apparently cares about cross compiling their popular framework for embedded - it's a shame.

**Comment by prabhakarlad** [comment]
thanks for that..

**Comment by lundmar** [comment]
Ok, boost is also updated to latest version. I can still build libftdi1 so I will assume it is okay but let me know if it fails.

**Comment by prabhakarlad** [comment]
great!!

**Pull request merged**
